#!/usr/bin/env Rscript
# crease_helicity.R -- reproduces the fractional magnetic helicity
# vartheta = alpha_Y * Sigma_W Y^2 of beyond/main/crease_helicity/CREASE_HELICITY.md.
#
# SOURCE: beyond/main/crease_helicity/CREASE_HELICITY.md sec 1.1 (the hypercharge sum
# table), sec 1.2 (alpha_Y running), sec 1.3 (the corrected APS coefficient
# vartheta = alpha * Sigma q^2, "not alpha Sigma q^2 / pi"), generated by
# crease_helicity.py in the same directory.
#
# 1. Sigma_W Y^2, the SM hypercharge-squared sum in the Q = T3 + Y convention
#    (CREASE_HELICITY.md sec 1.1 table), summed here directly from the field content:
#
#      field         mult   Y     mult*Y^2
#      Q_L (3c x 2w)   6   1/6      1/6
#      u_R^c           3  -2/3      4/3
#      d_R^c           3   1/3      1/3
#      L               2  -1/2      1/2
#      e_R^c           1   1        1
#      per generation ................ 10/3
#      x 3 generations ................ Sigma_W Y^2 = 10
#
#    cross-checked against the known SM one-loop hypercharge coefficient
#    b_Y = (2/3) Sigma_W Y^2 + (1/3) Sigma_scalar Y^2 = 20/3 + 1/6 = 41/6 (the SM
#    Higgs doublet has Y=1/2, so Sigma_scalar Y^2 = 1/2, i.e. (1/3)(1/2) = 1/6).
#
# 2. alpha_Y at the inflationary scale (sec 1.2), one-loop running from M_Z:
#
#      alpha_Y^-1(M_Z) = alpha_em^-1(M_Z) * cos^2(theta_W)      [Q=T3+Y convention]
#      d alpha_Y^-1 / d ln(mu) = -b_Y / (2 pi)
#      alpha_Y(mu) = 1 / [ alpha_Y^-1(M_Z) - (b_Y/2pi) ln(mu/M_Z) ]
#
#    with alpha_em^-1(M_Z) = 127.95, sin^2(theta_W) = 0.23122, M_Z = 91.1876 GeV,
#    M_P = 2.435e18 GeV (reduced Planck mass) -- all copied from crease_helicity.py.
#
# 3. vartheta = alpha_Y(H) * Sigma_W Y^2, "the fold's one unsuppressed perturbative
#    number" (CREASE_HELICITY.md HEADLINE): 0.1434 at H = 1e-5 M_P.
#
# Expected numbers (CREASE_HELICITY.md):
#   Sigma_W Y^2 = 10
#   alpha_Y(1e-5 M_P) = 0.014337 (= 1/69.75)
#   vartheta = 0.1434 at H = 1e-5 M_P  (quoted rounded as "0.143")

.args <- commandArgs(trailingOnly = FALSE)
.f <- sub("--file=", "", .args[grep("--file=", .args)])
.dir <- if (length(.f)) dirname(normalizePath(.f)) else "."
source(file.path(.dir, "helpers.R"))

section("crease_helicity.R -- CREASE_HELICITY.md sec 1, vartheta = alpha_Y * Sigma_W Y^2")

# ---------------------------------------------------------------------------
# 1. Sigma_W Y^2, from the SM field content (sec 1.1 table)
# ---------------------------------------------------------------------------
mult_Y2 <- c(QL = 6 * (1/6)^2, uRc = 3 * (2/3)^2, dRc = 3 * (1/3)^2,
             L = 2 * (1/2)^2, eRc = 1 * 1^2)
per_generation <- sum(mult_Y2)
SumWY2 <- 3 * per_generation

cat("\nHypercharge-squared sum per generation (Q=T3+Y convention):\n")
print(mult_Y2)
report("Sigma_W Y^2 per generation", 10/3, per_generation, tol = 1e-10)
report("Sigma_W Y^2 (x3 generations)", 10, SumWY2, tol = 1e-10)

bY <- (2/3) * SumWY2 + (1/3) * (1/2)   # Higgs doublet Y=1/2 -> Sigma_scalar Y^2 = 1/2
report("b_Y cross-check = (2/3)SigmaY^2 + (1/3)Sigma_scalar Y^2", 41/6, bY, tol = 1e-10,
       note = "known SM one-loop hypercharge coefficient")

# ---------------------------------------------------------------------------
# 2. alpha_Y at the inflationary scale (sec 1.2)
# ---------------------------------------------------------------------------
alpha_em_inv_MZ <- 127.95
sin2thetaW <- 0.23122
MZ <- 91.1876       # GeV
MP <- 2.435e18      # GeV, reduced Planck mass

alY_inv_MZ <- alpha_em_inv_MZ * (1 - sin2thetaW)   # alpha_Y^-1 = alpha_em^-1 cos^2(theta_W)
report("alpha_Y^-1(M_Z)", 98.365, alY_inv_MZ, tol = 0.001)

alpha_Y <- function(mu) 1 / (alY_inv_MZ - bY / (2 * pi) * log(mu / MZ))

H1 <- 1e-5 * MP
H2 <- 1e-7 * MP
aY1 <- alpha_Y(H1)
aY2 <- alpha_Y(H2)

cat(sprintf("\nH = 1e-5 M_P = %.4e GeV, H = 1e-7 M_P = %.4e GeV\n", H1, H2))
report("alpha_Y(1e-5 M_P)", 0.014337, aY1, tol = 0.001)
report("alpha_Y(1e-7 M_P)", 0.013376, aY2, tol = 0.001)

# ---------------------------------------------------------------------------
# 3. vartheta = alpha_Y(H) * Sigma_W Y^2 (HEADLINE)
# ---------------------------------------------------------------------------
vartheta1 <- aY1 * SumWY2
vartheta2 <- aY2 * SumWY2

cat("\nvartheta = alpha_Y(H) * Sigma_W Y^2:\n\n")
report("vartheta at H = 1e-5 M_P (rounded to 0.143)", 0.1434, vartheta1, tol = 0.001,
       note = "CREASE_HELICITY.md HEADLINE: 'vartheta = alpha_Y Sigma_W Y^2 = 0.143'")
report("vartheta at H = 1e-7 M_P", 0.1338, vartheta2, tol = 0.001)
