#!/usr/bin/env Rscript
# eta_rp4.R -- reproduces the Pin+ eta-invariant of RP^4 and the N_W phase table.
#
# SOURCE: beyond/main/spin_z4/SPIN_Z4.md sec 2.1 ("eta(RP^4) computed independently,
# and it lands on the literature value") and sec 2.2 ("The phase for N_W Weyl
# fermions"), generated by eta_rp4.py in beyond/main/spin_z4/.
#
# The closed form (SPIN_Z4.md sec 2.1, s0 = +1 branch):
#
#   eta_{RP4}(0) = (2/3) [ -(1-2^4) zeta(-3) + (1-2^2) zeta(-1) ] = (2/3)(1/8+1/4) = 1/4
#
# using the standard values zeta(-1) = -1/12, zeta(-3) = 1/120 (quoted in the record;
# these are well-known exact values of the Riemann zeta function at negative odd
# integers, not derived here -- eta_rp4.py obtains the same closed form via sympy's
# symbolic zeta and analytic continuation of the alternating sum, and cross-checks it
# against a direct numerical sum at s=6 to 1.2e-17; that derivation is not repeated
# here, only its algebraic closed form is evaluated).
#
# This matches Witten 1508.04715 fn. 39 verbatim, quoted in SPIN_Z4.md: "For X = RP4,
# one has exp(-i pi eta/2) = exp(+-2 i pi/16)", i.e. eta(RP^4) = -+1/4.
#
# The N_W Weyl-fermion phase table (SPIN_Z4.md sec 2.2 / eta_rp4.py part C): taking
# one Pin+ Majorana per 4d Weyl fermion, N_W of them give a partition-function phase
#
#   Z_+- = |Z| * exp(+- i pi N_W / 8)
#
# reproduced here for N_W = 45 (three SM generations, no nu_R) and N_W = 48 (three
# generations with nu_R), matching eta_rp4_output.txt's table rows for NW=45, NW=48.

.args <- commandArgs(trailingOnly = FALSE)
.f <- sub("--file=", "", .args[grep("--file=", .args)])
.dir <- if (length(.f)) dirname(normalizePath(.f)) else "."
source(file.path(.dir, "helpers.R"))

section("eta_rp4.R -- SPIN_Z4.md sec 2.1 eta(RP4) and sec 2.2 N_W phase table")

# ---------------------------------------------------------------------------
# eta(RP^4)
# ---------------------------------------------------------------------------
zeta_m1 <- -1 / 12   # zeta(-1), quoted exact value
zeta_m3 <- 1 / 120   # zeta(-3), quoted exact value

eta_RP4 <- (2 / 3) * (-(1 - 2^4) * zeta_m3 + (1 - 2^2) * zeta_m1)

cat(sprintf("\nzeta(-1) = %s, zeta(-3) = %s (quoted exact values)\n", zeta_m1, zeta_m3))
report("eta(RP^4) = (2/3)[-(1-2^4)zeta(-3)+(1-2^2)zeta(-1)]", 0.25, eta_RP4, tol = 1e-10,
       note = "SPIN_Z4.md sec 2.1; Witten 1508.04715 fn.39: eta(RP4) = -+1/4")

# ---------------------------------------------------------------------------
# N_W phase table
# ---------------------------------------------------------------------------
cat("\nPhase table Z_+- = exp(+- i pi N_W / 8) (SPIN_Z4.md sec 2.2 / eta_rp4.py part C):\n\n")

phase_table <- function(NW) {
  zplus  <- complex(modulus = 1, argument =  pi * NW / 8)
  zminus <- complex(modulus = 1, argument = -pi * NW / 8)
  list(NW = NW, mod16 = NW %% 16, mod8 = NW %% 8, zplus = zplus, zminus = zminus,
       summed = 2 * cos(pi * NW / 8))
}

# N_W = 45: three SM generations, no right-handed neutrino (n = N_W mod 16 = 13)
p45 <- phase_table(45)
cat(sprintf("N_W=45 (3 generations, no nu_R): mod16=%d, mod8=%d\n", p45$mod16, p45$mod8))
report("Re[exp(+i pi*45/8)]", 0.382683, Re(p45$zplus), tol = 1e-5, mode = "abs")
report("Im[exp(+i pi*45/8)]", -0.923880, Im(p45$zplus), tol = 1e-5, mode = "abs")
report("Re[exp(-i pi*45/8)]", 0.382683, Re(p45$zminus), tol = 1e-5, mode = "abs")
report("Im[exp(-i pi*45/8)]", 0.923880, Im(p45$zminus), tol = 1e-5, mode = "abs")
report("2cos(pi*45/8) [summed lift weight]", 0.765367, p45$summed, tol = 1e-5, mode = "abs")

# N_W = 48: three SM generations with nu_R (n = N_W mod 16 = 0)
p48 <- phase_table(48)
cat(sprintf("\nN_W=48 (3 generations with nu_R): mod16=%d, mod8=%d\n", p48$mod16, p48$mod8))
report("Re[exp(+i pi*48/8)]", 1.0, Re(p48$zplus), tol = 1e-10, mode = "abs")
report("Im[exp(+i pi*48/8)]", 0.0, Im(p48$zplus), tol = 1e-10, mode = "abs")
report("2cos(pi*48/8) [summed lift weight]", 2.0, p48$summed, tol = 1e-10, mode = "abs")

cat("\nRead-off (SPIN_Z4.md sec 2.2): N_W=45 has n=13, 2cos(13pi/8)=+0.765>0, so it PASSES\n")
cat("the sign-definiteness/non-vanishing tests but FAILS the phase-exactly-1 and\n")
cat("phase-real tests; N_W=48 has n=0 and passes everything.\n")
