#!/usr/bin/env Rscript
# firsttick.R -- reproduces the first-tick branch-decoherence closed form and its
# three headline numbers.
#
# SOURCE: beyond/main/first_tick/FIRST_TICK.md  section 2.4 ("The closed form"), and
#         the HEADLINE table at the top of that file. The formula and every quoted
#         number below is copied from that file (which in turn is generated by
#         branch_overlap.py / branch_overlap_output.txt in the same directory).
#
# Closed form (FIRST_TICK.md sec 2.4):
#
#   log|<E_-|E_+>| = -(N_f/4) * SUM_{n>=2} n^2 * log[ 1 + A^4(A^2-1)/(n^2(n^2-1)^2) ]
#                                                                       A := aH
#
# Gamma-bar (DM_CLOCK.md's / FIRST_TICK.md's usage) is the negative log-overlap,
# Gamma = -log|D|, so "the overlap falls below e^-1" <=> Gamma = 1 <=> log|D| = -1.
# FIRST_TICK.md HEADLINE table: A_dec = 1.95376 for one field (all n>=2, "unfolded"),
# and A_dec = 2.59540 for the same field on the folded RP^3 slice, where the fold
# deletes the even-n harmonics ("only odd n survive on RP3", FIRST_TICK.md sec 4c).
#
# Large-A asymptote (sec 2.4): log|D| -> -(pi/12) N_f A^3, "good to 0.07% by A = 10
# (exact -261.627 vs -261.799)".
#
# No new physics and no re-derivation: this script only evaluates the formula
# FIRST_TICK.md already states, and root-finds A_dec from it exactly as that file
# describes ("falls below e^-1").

.args <- commandArgs(trailingOnly = FALSE)
.f <- sub("--file=", "", .args[grep("--file=", .args)])
.dir <- if (length(.f)) dirname(normalizePath(.f)) else "."
source(file.path(.dir, "helpers.R"))

section("firsttick.R -- FIRST_TICK.md sec 2.4 closed form and A_dec roots")

# ---------------------------------------------------------------------------
# The closed form. nmax is chosen so the tail is far below double precision:
# the summand falls off as ~1/n^4 for large n, so by n = 2e5 the neglected
# tail is O(1e-20) relative to terms of order 1 -- utterly negligible here.
# ---------------------------------------------------------------------------
log_abs_D <- function(A, Nf = 1, odd_only = FALSE, nmax = 2e5) {
  n <- 2:nmax
  if (odd_only) n <- n[n %% 2 == 1]
  x <- A^4 * (A^2 - 1) / (n^2 * (n^2 - 1)^2)
  -(Nf / 4) * sum(n^2 * log1p(x))
}

# Gamma(A) := -log|D(A)|; we solve Gamma(A) = 1, i.e. log|D| = -1.
Gamma_minus_1 <- function(A, ...) -log_abs_D(A, ...) - 1

cat("\nSolving Gamma(A) := -log|D(A)| = 1 (\"the overlap falls below e^-1\"):\n\n")

# --- (1) N_f = 1, unfolded (all n >= 2) -------------------------------------
root_unfolded <- uniroot(Gamma_minus_1, interval = c(1.01, 5), Nf = 1, odd_only = FALSE,
                          tol = 1e-12)
A_dec_unfolded <- root_unfolded$root
Ht_dec_unfolded <- acosh(A_dec_unfolded)  # from a(t) = cosh(Ht)/H => A = aH = cosh(Ht)

report("A_dec, N_f=1, unfolded (all n>=2)", 1.95376, A_dec_unfolded, tol = 1e-4,
       note = "FIRST_TICK.md HEADLINE table, row 'one field'")
report("H*t_dec, N_f=1, unfolded (derived: Ht=acosh(A), FIRST_TICK.md sec 2.1)",
       1.28984, Ht_dec_unfolded, tol = 1e-4)

# --- (2) N_f = 1, folded RP^3 (odd n only) ----------------------------------
root_folded <- uniroot(Gamma_minus_1, interval = c(1.01, 5), Nf = 1, odd_only = TRUE,
                        tol = 1e-12)
A_dec_folded <- root_folded$root
Ht_dec_folded <- acosh(A_dec_folded)

report("A_dec, N_f=1, folded RP^3 (odd n only)", 2.59540, A_dec_folded, tol = 1e-4,
       note = "FIRST_TICK.md HEADLINE table, row 'one field, folded (RP3)'")
report("H*t_dec, N_f=1, folded RP^3 (derived: Ht=acosh(A))",
       1.60752, Ht_dec_folded, tol = 1e-4)

delay_pct <- 100 * (A_dec_folded / A_dec_unfolded - 1)
report("fold delay in A_dec (%) [text: 'delays its own first tick by 33%']",
       33, delay_pct, tol = 0.03, mode = "rel",
       note = "sec 4c: 'the fold delays its own first tick by 33% in a'")

# ---------------------------------------------------------------------------
# Large-A asymptote check at A = 10, N_f = 1 (sec 2.4):
#   exact log|D|(10) = -261.627,  asymptote -(pi/12)*10^3 = -261.799,
#   claimed agreement: 0.07%
# ---------------------------------------------------------------------------
cat("\nLarge-A asymptote check at A = 10, N_f = 1 (sec 2.4):\n\n")

A10 <- 10
exact_10 <- log_abs_D(A10, Nf = 1, odd_only = FALSE)
asym_10 <- -(pi / 12) * 1 * A10^3

report("exact log-abs-D at A=10, N_f=1", -261.627, exact_10, tol = 1e-4)
report("asymptote -(pi/12) N_f A^3 at A=10", -261.799, asym_10, tol = 1e-4)

pct_disagree <- 100 * abs(exact_10 - asym_10) / abs(exact_10)
report("asymptote vs exact relative disagreement (%) [text: '0.07%']",
       0.07, pct_disagree, tol = 0.01, mode = "abs",
       note = "abs tol in *percentage points*, since source quotes only 2 sig figs")

cat("\nSummary table (all from FIRST_TICK.md HEADLINE):\n")
cat(sprintf("  %-34s %12s %12s\n", "case", "A_dec", "H*t_dec"))
cat(sprintf("  %-34s %12.5f %12.5f\n", "one field (unfolded)", A_dec_unfolded, Ht_dec_unfolded))
cat(sprintf("  %-34s %12.5f %12.5f\n", "one field, folded (RP3)", A_dec_folded, Ht_dec_folded))
