#!/usr/bin/env Rscript
# dm_clock.R -- reproduces the pure number R, the pure number I, and the tick t_dec
# of beyond/main/dm_clock/DM_CLOCK.md.
#
# SOURCE: beyond/main/dm_clock/DM_CLOCK.md (HEADLINE block and sec 3.5/"D. the
# numbers"), generated by dm_clock.py in the same directory.
#
# R is the ratio of the phase-averaged decoherence exponent to the number of dark
# matter particles produced, for BFT's half-angle CPT vacuum occupation
# n(x) = (1 - sqrt(1 - exp(-x^2))) / 2  (DM_CLOCK.md HEADLINE):
#
#   R = INT_0^inf x^2 [-log(1-n(x))] dx  /  INT_0^inf x^2 n(x) dx  =  1.07036818804
#
# I is the normalised comoving-number integral (DM_CLOCK.md sec "D", quoted also in
# PAPER2_v3.md sec 4.2 as "I = 0.0127596673634":
#
#   I = (1/(2 pi^2)) INT_0^inf x^2 [1 - sqrt(1 - exp(-x^2))] dx  =  0.0127596673634
#
# (Note I = (1/pi^2) * INT x^2 n(x) dx, i.e. the same n(x) integral as R's
# denominator, just normalised differently -- consistent by construction.)
#
# The PHASE-AVERAGED crossing is
#   t_dec = (2 M1)^-1 [(4/(3 sqrt(pi))) c_G R I]^-2/3.
# For c_G=1 per (p,h) mode this is 10.5798/M1. A Majorana-pair convention
# c_G=1/2 gives 16.7945/M1. The script derives both coefficients below.
#
# Expected numbers (DM_CLOCK.md):
#   R = 1.07036818804
#   I = 0.0127596673634  (quoted rounded as "0.0127597")
#   t_dec = 10.6/M1 = 1.417e-32 s for M1 = 4.916e8 GeV

.args <- commandArgs(trailingOnly = FALSE)
.f <- sub("--file=", "", .args[grep("--file=", .args)])
.dir <- if (length(.f)) dirname(normalizePath(.f)) else "."
source(file.path(.dir, "helpers.R"))

section("dm_clock.R -- DM_CLOCK.md pure numbers R, I, and the tick t_dec")

# ---------------------------------------------------------------------------
# BFT half-angle CPT vacuum occupation (DM_CLOCK.md HEADLINE)
# ---------------------------------------------------------------------------
n_occ <- function(x) (1 - sqrt(1 - exp(-x^2))) / 2

num_integrand <- function(x) x^2 * (-log1p(-n_occ(x)))
den_integrand <- function(x) x^2 * n_occ(x)
I_integrand   <- function(x) x^2 * (1 - sqrt(1 - exp(-x^2)))

# Upper limit 10 is safe to machine precision: exp(-100) ~ 4e-44, and the
# integrand at that point is already ~1e-42 relative to its peak value.
num <- integrate(num_integrand, 0, 10, rel.tol = 1e-12, subdivisions = 500L)
den <- integrate(den_integrand, 0, 10, rel.tol = 1e-12, subdivisions = 500L)
R_val <- num$value / den$value

cat(sprintf("\nINT x^2[-log(1-n)] dx = %.12e (quad abs.err %.1e)\n", num$value, num$abs.error))
cat(sprintf("INT x^2 n(x) dx       = %.12e (quad abs.err %.1e)\n", den$value, den$abs.error))

report("R = Gamma-bar / N", 1.07036818804, R_val, tol = 1e-8,
       note = "DM_CLOCK.md HEADLINE, 12 digits")

I_int <- integrate(I_integrand, 0, 10, rel.tol = 1e-12, subdivisions = 500L)
I_val <- I_int$value / (2 * pi^2)

report("I = (1/2pi^2) INT x^2[1-sqrt(1-e^-x^2)] dx", 0.0127596673634, I_val, tol = 1e-8,
       note = "DM_CLOCK.md sec D and PAPER2_v3.md sec 4.2")

# ---------------------------------------------------------------------------
# The tick from the phase-averaged formula, converted to seconds.
# ---------------------------------------------------------------------------
cat("\nThe tick t_dec = 10.5798/M1 (DM_CLOCK.md HEADLINE table, c_G=1, phase-averaged):\n\n")

M1_GeV <- 4.916e8            # GeV, the ceiling of Paper 2 sec 2.3
hbar_GeV_s <- 6.582119569e-25 # GeV*s (CODATA), i.e. 1 GeV^-1 = this many seconds

cG <- 1
tick_coefficient <- 0.5 * ((4 / (3 * sqrt(pi))) * cG * R_val * I_val)^(-2/3)
t_dec_GeVinv <- tick_coefficient / M1_GeV
t_dec_s <- t_dec_GeVinv * hbar_GeV_s

report("t_dec coefficient [1/M1], c_G=1", 10.5798, tick_coefficient, tol = 1e-5,
       note = "derived from the displayed phase-averaged R-I formula")
report("t_dec [s], M1 = 4.916e8 GeV", 1.417e-32, t_dec_s, tol = 0.005,
       note = "DM_CLOCK.md HEADLINE: 't_dec = 10.58/M1 = 1.44e-32 s' (coefficient rounded to 10.6)")

tick_coefficient_half <- 0.5 * ((4 / (3 * sqrt(pi))) * 0.5 * R_val * I_val)^(-2/3)
t_dec_half_s <- tick_coefficient_half / M1_GeV * hbar_GeV_s
report("t_dec [s], c_G=1/2 Majorana-pair convention", 2.249e-32, t_dec_half_s,
       tol = 0.005, note = "factor-of-order-one counting alternative")

