# Re-deriving the Clausius step rather than citing it.
#
# Section 3.6 leans on Jacobson's 1995 derivation. Leaning on a citation is an argument from
# authority, and it is the beam the whole gravity claim rests on, so it gets re-derived here with
# each step checked rather than asserted. The fold's contribution is the temperature and the
# horizons; what is being checked is that those two plus an area-proportional entropy really do
# force the field equations, and with which assumptions.
#
# 2026-10-06: written when (ii) and the universality half of (iv) were still assumed. Both are
# derived now, in area_law_from_fold.R, eta_is_universal.R and universality_local_fold.R, and
# sections 1 and 6 say so after the original wording. Nothing computed here changed.

cat("=== 1. the construction, stated so the assumptions are countable ===\n")
cat("   At a point p pick a null direction k. Erect the past horizon of a uniformly accelerated\n")
cat("   observer with p on its bifurcation surface, generated by the boost Killing field which\n")
cat("   near p is chi^a = -kappa lambda k^a, lambda the affine parameter with lambda = 0 at p.\n")
cat("   Four assumptions, and they are the whole list:\n")
cat("      (i)   the Unruh temperature T = kappa / 2 pi holds on that horizon\n")
cat("      (ii)  the entropy is eta times the area, with eta the same at every such horizon\n")
cat("      (iii) the Clausius relation dQ = T dS holds for the matter flux across it\n")
cat("      (iv)  every point and every null direction admits such a horizon\n")
cat("   The fold supplies (i) and supplies the horizons of (iv) at every boost and orientation,\n")
cat("   since J P = -Id is frame-independent. (ii) and the universality half of (iv) are assumed\n")
cat("   here exactly as they are assumed in the original.\n")
cat("   That was so when this was written and is not now: area_law_from_fold.R derives (ii)'s\n")
cat("   area law, eta_is_universal.R the universality of its coefficient, and\n")
cat("   universality_local_fold.R the horizons of (iv) away from the fold's fixed locus. This\n")
cat("   script checks the Clausius step itself, which is the same either way.\n")

cat("\n=== 2. the area change, from Raychaudhuri, integrated rather than quoted ===\n")
cat("   dtheta/dlambda = -theta^2/2 - sigma_shear^2 - R_kk. Near the bifurcation surface theta\n")
cat("   and the shear vanish, so both quadratic terms are second order and theta = -lambda R_kk\n")
cat("   to leading order. Integrate the full equation and check that:\n")
ray <- function(Rkk, lam_max = 0.25, n = 200000) {
  h <- lam_max / n; th <- 0; out <- numeric(n + 1)
  for (i in 1:n) {                                  # theta' = -theta^2/2 - Rkk, shear zero
    k1 <- -th^2 / 2 - Rkk
    k2 <- -(th + h/2 * k1)^2 / 2 - Rkk
    k3 <- -(th + h/2 * k2)^2 / 2 - Rkk
    k4 <- -(th + h * k3)^2 / 2 - Rkk
    th <- th + h / 6 * (k1 + 2*k2 + 2*k3 + k4); out[i + 1] <- th
  }
  list(lam = seq(0, lam_max, length.out = n + 1), theta = out)
}
cat("      R_kk    lambda    theta integrated    -lambda R_kk    relative error\n")
for (Rkk in c(0.3, 1.0)) {
  s <- ray(Rkk)
  for (L in c(0.01, 0.05)) {
    i <- which.min(abs(s$lam - L))
    cat(sprintf("   %7.2f  %8.3f  %18.8f  %14.8f  %14.2e\n",
                Rkk, L, s$theta[i], -L * Rkk, abs(s$theta[i] / (-L * Rkk) - 1)))
    stopifnot(abs(s$theta[i] / (-L * Rkk) - 1) < 2e-3)
  }
}
cat("   So delta A = int theta dlambda dA = - int lambda R_kk dlambda dA, with the quadratic\n")
cat("   terms entering at the next order. That is the step, and it is a measurement here.\n")

cat("\n=== 3. the heat flux, and the factor the two sides share ===\n")
cat("   dQ = int T_ab chi^a dSigma^b = -kappa int lambda T_kk dlambda dA. Both sides therefore\n")
cat("   carry the same int lambda ... dlambda dA, and with T = kappa/2 pi and dS = eta dA the\n")
cat("   Clausius relation reduces to a pointwise statement with the kappa cancelling:\n")
cat("        -kappa int lambda T_kk = (kappa/2 pi) eta ( - int lambda R_kk )\n")
cat("        =>   2 pi T_kk = eta R_kk   for every null k at p.\n")
cat("   The kappa cancels, which is why no acceleration scale appears in the answer.\n")

cat("\n=== 4. the algebraic step: from all null k to a tensor equation ===\n")
cat("   Write S_ab = 2 pi T_ab - eta R_ab. The previous line says S_ab k^a k^b = 0 for EVERY\n")
cat("   null k. The claim is that this forces S_ab = f g_ab. That is linear algebra and it is\n")
cat("   checked here on random symmetric tensors rather than asserted.\n")
set.seed(7)
eta_m <- diag(c(-1, 1, 1, 1))
rand_null <- function() {
  v <- rnorm(3); n <- sqrt(sum(v^2)); c(1, v / n) * runif(1, 0.5, 2)
}
# build the linear map S -> (S_ab k^a k^b) for many null k and find its kernel
nk <- 60
K <- matrix(0, nk, 10)
idx <- which(upper.tri(diag(4), diag = TRUE), arr.ind = TRUE)
for (i in 1:nk) {
  k <- rand_null()
  K[i, ] <- apply(idx, 1, function(ij) {
    a <- ij[1]; b <- ij[2]; (if (a == b) 1 else 2) * k[a] * k[b]
  })
}
sv <- svd(K)
cat(sprintf("      singular values of the constraint map, smallest three: %.3e %.3e %.3e\n",
            sv$d[10], sv$d[9], sv$d[8]))
ker <- sv$v[, 10]
Smat <- matrix(0, 4, 4)
for (r in 1:10) { a <- idx[r,1]; b <- idx[r,2]; Smat[a,b] <- ker[r]; Smat[b,a] <- ker[r] }
Smat <- Smat / Smat[1, 1] * eta_m[1, 1]
cat("      the one-dimensional kernel, normalised, against the Minkowski metric:\n")
for (i in 1:4) cat(sprintf("        %+8.5f %+8.5f %+8.5f %+8.5f     %+5.1f %+5.1f %+5.1f %+5.1f\n",
                           Smat[i,1], Smat[i,2], Smat[i,3], Smat[i,4],
                           eta_m[i,1], eta_m[i,2], eta_m[i,3], eta_m[i,4]))
cat(sprintf("      worst departure from g_ab: %.2e, and the kernel is one-dimensional since the\n",
            max(abs(Smat - eta_m))))
cat(sprintf("      ninth singular value is %.2e, larger than the tenth by %.0e\n",
            sv$d[9], sv$d[9] / sv$d[10]))
stopifnot(max(abs(Smat - eta_m)) < 1e-9, sv$d[9] / sv$d[10] > 1e6)
cat("   So S_ab = f g_ab, with f a function and not a constant at this stage.\n")

cat("\n=== 5. fixing f, where the Bianchi identity does the work ===\n")
cat("   2 pi T_ab = eta R_ab + f g_ab. Take the divergence. Matter conservation gives\n")
cat("   grad^a T_ab = 0, and the contracted Bianchi identity gives grad^a R_ab = grad_b R / 2, so\n")
cat("        0 = eta grad_b R / 2 + grad_b f   =>   f = -eta R/2 + Lambda eta\n")
cat("   with Lambda an integration constant. Substituting,\n")
cat("        R_ab - R g_ab / 2 + Lambda g_ab = (2 pi / eta) T_ab,\n")
cat("   which is the Einstein equation with 8 pi G = 2 pi / eta, that is eta = 1/4G.\n")
cat("   Lambda is an integration constant of this derivation and is not predicted by it.\n")

cat("\n=== 6. what the re-derivation changes about the claim ===\n")
cat("   Nothing in the conclusion and something in the standing. The three inputs the fold\n")
cat("   supplies are (i) and the horizons of (iv), and those are now used rather than cited.\n")
cat("   When this was written, what remained assumed was (ii), an area-proportional entropy with\n")
cat("   a universal coefficient, and the universality half of (iv), both as in the original. Both\n")
cat("   are derived now (area_law_from_fold.R, eta_is_universal.R, universality_local_fold.R),\n")
cat("   and the manuscript counts them as derived. What remains assumed is (iii), the Clausius\n")
cat("   relation itself, and the measured value of eta.\n")
cat("   One thing the re-derivation makes visible that a citation would not: the acceleration\n")
cat("   kappa cancels between the two sides, so the result does not depend on how hard the\n")
cat("   observer accelerates, which is what lets a local statement become a field equation.\n")

cat("\n=== 7. the plants ===\n")
cat("   (a) the null-vector argument must FAIL for timelike vectors, or it proves too much.\n")
Kt <- matrix(0, nk, 10)
for (i in 1:nk) {
  v <- rnorm(3) * 0.3; k <- c(1, v)                 # timelike, not null
  Kt[i, ] <- apply(idx, 1, function(ij) {
    a <- ij[1]; b <- ij[2]; (if (a == b) 1 else 2) * k[a] * k[b] })
}
svt <- svd(Kt)
cat(sprintf("      with timelike vectors the smallest singular value is %.3e, so the kernel is\n",
            svt$d[10]))
cat("      empty and S_ab = 0 rather than f g_ab. Null is doing real work.\n")
stopifnot(svt$d[10] > 1e-6)
cat("   (b) Raychaudhuri's linear regime must break when it should.\n")
s <- ray(1.0)
for (L in c(0.05, 0.2)) {
  i <- which.min(abs(s$lam - L))
  cat(sprintf("      lambda = %.2f: theta = %+.6f against -lambda R_kk = %+.6f, error %.1e\n",
              L, s$theta[i], -L, abs(s$theta[i] / (-L) - 1)))
}
cat("      The error grows with lambda as the theta^2 term bites, which is the expansion being\n")
cat("      an expansion and not an identity.\n")
