# The null-momentum route to the contact amplitude, and why the standard caustic tool is wrong here.
#
# planewave_null_caustic.R showed a vacuum null caustic has no invariant length, so the amplitude
# rides on the null momentum rather than on a geometric scale. This works out what that means.
#
# THE FIRST THING IT SETTLES IS WHICH TOOL. At a generic fold caustic the classical action has a
# CUBIC stationary point in the family parameter and the uniform replacement for the failed
# parametrix is an Airy function. That is not this. Here the degenerate direction is generated by a
# ROTATION Killing field, so the action is exactly independent of the family parameter: every member
# of the family is an isometric image of every other and they all have the same action. The
# degeneracy is a symmetry degeneracy and not an accidental one, so it is not resolved by a cubic
# term. It is resolved by integrating the symmetry orbit exactly, which is a collective coordinate
# and not an Airy function. Reaching for Airy here would have produced a wrong answer confidently.

cat("=== 1. the action is flat along the family, checked ===\n")
cat("   The family is the circle of planes through the axis, parametrised by the rotation angle\n")
cat("   zeta. A rotation is an isometry of the geometry and maps the contact geodesic to another\n")
cat("   member of the family, so every member has the same length, the same Jacobi fields and the\n")
cat("   same action. Check it on the closed form: the geodesic is r(phi) = M(1 + sin phi) in every\n")
cat("   plane, so the affine length cannot depend on zeta.\n")
lam <- function(zeta) integrate(function(p) (1 + sin(p))^2, 0, pi)$value  # zeta enters nowhere
vals <- sapply(seq(0, 2 * pi, length.out = 9), lam)
cat(sprintf("   affine length over nine rotations: spread %.2e about %.6f\n",
            diff(range(vals)), mean(vals)))
stopifnot(diff(range(vals)) < 1e-12)
cat("   Flat. A cubic stationary point needs curvature in the family direction and there is none.\n")

cat("\n=== 2. the propagator in the Penrose limit, which is exact for the transverse structure ===\n")
cat("   Fourier in V with null momentum p turns the wave equation into a Schrodinger equation in\n")
cat("   the affine parameter U, with mass p and a time-dependent quadratic potential fixed by the\n")
cat("   tidal. The kernel is Gaussian and exact, with amplitude 1/sqrt(J1 J2) built from the very\n")
cat("   Jacobi solutions contact_vanvleck.R computes:\n")
lam_tot <- 3 * pi / 2 + 4; J2end <- 47.561945
cat(sprintf("      J1(lambda_tot) = 0 exactly,   J2(lambda_tot) = %.6f,   lambda_tot = %.6f\n",
            J2end, lam_tot))
cat("   J1 vanishing is the caustic, and it is why the naive kernel diverges.\n")

cat("\n=== 3. the dictionary between the two languages, and the power it fixes ===\n")
cat("   The Riemannian side gave Delta^{1/2} -> c_n s^{-n/2} at an n-fold degenerate family, with\n")
cat("   s the heat-kernel proper time. In the Lorentzian propagator the conjugate variable is the\n")
cat("   null momentum, s <-> 1/p, so the same replacement reads\n")
cat("        each zero mode contributes an EXTRA factor p^{1/2}.\n")
cat("   The non-degenerate transverse kernel already carries p^{1/2} per direction, so in D = 4\n")
cat("   with n degenerate directions the p-weight is p^{1 + n/2} rather than p.\n\n")
cat("      n    p-weight     int dp p^w e^{-i p DV}    DV exponent\n")
for (n in 0:3) {
  w <- 1 + n / 2
  cat(sprintf("   %4d    p^%-8.1f  Gamma(%.1f)/(i DV)^{%.1f}       %+.1f\n", n, w, w + 1, w + 1, -(w + 1)))
}
cat("\n   Test that against the rule antipodal_sphere_family.R fixed on five points. The world\n")
cat("   function goes as DV near a null pair, so an exponent -(1 + n/2 + 1) in DV is an exponent\n")
cat("   -(2 + n/2) in sigma for the FULL propagator, whose non-degenerate value must be the\n")
cat("   generic -(D-2)/2 = -1 in sigma at D = 4. The offset between the two conventions is fixed\n")
cat("   by the n = 0 row, and once fixed the n dependence must match:\n")
off <- -(0 + 2) - (-1)          # the n = 0 row against the known generic value
cat(sprintf("      offset fixed at n = 0: %+.1f\n", off))
for (n in 0:3) {
  pred <- -(2 + n / 2) - off
  rule <- -(4 - 2 + n) / 2
  cat(sprintf("      n = %d:  null-momentum route %+.1f   rule -(D-2+n)/2 %+.1f   %s\n",
              n, pred, rule, ifelse(abs(pred - rule) < 1e-12, "agree", "DISAGREE")))
  stopifnot(abs(pred - rule) < 1e-12)
}
cat("   The n dependence matches at every order, which is the bridge between the Riemannian\n")
cat("   heat-kernel language and the Lorentzian one holding. One extra half power of p per\n")
cat("   degenerate direction is the same statement as one extra half power of sigma.\n")

cat("\n=== 4. so what is left is one number, and it is named ===\n")
cat("   With the power settled, the amplitude is the collective-coordinate Jacobian for the\n")
cat("   rotation zero mode: the orbit's volume, 2 pi, times the norm the Gaussian measure assigns\n")
cat("   to the Killing displacement xi(lambda) = r sin(phi), with the mass p in the measure. That\n")
cat("   is a one-dimensional quadrature over the closed-form curve and nothing more:\n")
xi2 <- integrate(function(p) ((1 + sin(p)) * sin(p))^2 * (1 + sin(p))^2, 0, pi)$value / lam_tot
cat(sprintf("      orbit volume                 2 pi = %.6f\n", 2 * pi))
cat(sprintf("      <xi^2> along the curve            = %.6f M^2\n", xi2))
cat(sprintf("      spreading partner at the end J2   = %.6f\n", J2end))
cat("   What is NOT settled is the p-dependence of that Jacobian's normalisation, which is where\n")
cat("   the earlier Riemannian route hid its length. Getting it wrong is exactly the mistake that\n")
cat("   produced two withdrawn numbers, so it is not being guessed here.\n")

cat("\n=== 5. the plant ===\n")
cat("   (a) the bridge must fail if the extra power per zero mode is anything but a half.\n")
for (h in c(0.25, 0.5, 1.0)) {
  ok <- TRUE
  for (n in 0:3) {
    pred <- -(2 + n * h) - off; rule <- -(2 + n) / 2
    if (abs(pred - rule) > 1e-12) ok <- FALSE
  }
  cat(sprintf("      extra power %.2f per zero mode:  %s\n", h,
              ifelse(ok, "matches the rule at every n", "fails, as it must")))
  if (abs(h - 0.5) > 1e-9) stopifnot(!ok)
}
cat("   (b) and the flat-action check must notice a family that is NOT a symmetry orbit.\n")
fake <- sapply(seq(0, 2*pi, length.out = 9), function(z) (3*pi/2 + 4) * (1 + 0.05 * cos(z)))
cat(sprintf("      a family with a 5 per cent modulation: spread %.4f, which the test rejects\n",
            diff(range(fake))))
stopifnot(diff(range(fake)) > 1e-3)
